export const planetData = [
    {
      id: 'mercury',
      name: "MERCURY",
      radius: 5,
      size: 0.38,
      color: "#A9A9A9",
      speed: 0.8,
      texture: "/2k_mercury.jpg",
      info: "The smallest planet in our solar system and closest to the Sun. Mercury is only slightly larger than Earth's Moon with extreme temperature variations from 800°F (430°C) during the day to -290°F (-180°C) at night.",
      class: "ROCKY PLANET",
      gravity: "0.38G",
      temp: "100-700K",
      atmosphere: "TRACE",
      hasRings: false,
      inclination: 7.0,
      music: '/sound.mp3',
      discovery: "Known to ancients",
      moons: 0,
      orbitalPeriod: "88 Earth days"
    },
    {
      id: 'venus',
      name: "VENUS",
      radius: 8,
      size: 0.95,
      color: "#E6C229",
      speed: 0.6,
      texture: "/2k_venus.jpg",
      info: "The hottest planet with a toxic atmosphere of carbon dioxide. Venus rotates in the opposite direction of most planets with a day longer than its year. Surface pressure is 92 times that of Earth's.",
      class: "TERRESTRIAL",
      gravity: "0.91G",
      temp: "735K",
      atmosphere: "CO₂ (96.5%)",
      hasRings: false,
      inclination: 3.4,
      music: '/sound.mp3',
      discovery: "Known to ancients",
      moons: 0,
      orbitalPeriod: "225 Earth days"
    },
    {
      id: 'earth',
      name: "EARTH",
      radius: 12,
      size: 1.0,
      color: "#1E90FF",
      speed: 0.4,
      texture: "/2k_earth.jpg",
      info: "Our home planet with abundant liquid water and life. Earth is the only known planet with active plate tectonics and a strong magnetic field that protects life from solar radiation.",
      class: "TERRESTRIAL",
      gravity: "1.0G",
      temp: "288K",
      atmosphere: "N₂ (78%), O₂ (21%)",
      hasRings: false,
      inclination: 0.0,
      music: '/sound.mp3',
      discovery: "N/A",
      moons: 1,
      orbitalPeriod: "365.25 days"
    },
    {
      id: 'mars',
      name: "MARS",
      radius: 16,
      size: 0.53,
      color: "#E27B58",
      speed: 0.3,
      texture: "/2k_mars.jpg",
      info: "The Red Planet with the largest volcano in the solar system (Olympus Mons). Mars has seasons, polar ice caps, and evidence of ancient liquid water. Dust storms can cover the entire planet.",
      class: "ROCKY PLANET",
      gravity: "0.38G",
      temp: "210K",
      atmosphere: "CO₂ (95%)",
      hasRings: false,
      inclination: 1.9,
      music: '/sound.mp3',
      discovery: "Known to ancients",
      moons: 2,
      orbitalPeriod: "687 Earth days"
    },
    {
      id: 'jupiter',
      name: "JUPITER",
      radius: 22,
      size: 1.12,
      color: "#C88B3A",
      speed: 0.2,
      texture: "/2k_jupiter.jpg",
      info: "The largest planet with a Great Red Spot storm that has raged for centuries. Jupiter's massive magnetic field is 20,000 times stronger than Earth's. It has 79 known moons including Ganymede, the largest moon in the solar system.",
      class: "GAS GIANT",
      gravity: "2.53G",
      temp: "165K",
      atmosphere: "H₂ (90%), He (10%)",
      hasRings: false,
      inclination: 1.3,
      music: '/sound.mp3',
      discovery: "Known to ancients",
      moons: 79,
      orbitalPeriod: "12 Earth years"
    },
    {
      id: 'saturn',
      name: "SATURN",
      radius: 28,
      size: 0.94,
      color: "#E3DCCB",
      speed: 0.15,
      texture: "/2k_saturn.jpg",
      info: "Known for its beautiful ring system made of ice and rock particles. Saturn is the least dense planet - it would float in water. The planet has powerful jet streams reaching 1,800 km/h.",
      class: "GAS GIANT",
      gravity: "1.07G",
      temp: "134K",
      atmosphere: "H₂ (96%), He (3%)",
      hasRings: true,
      inclination: 2.5,
      music: '/sound.mp3',
      discovery: "Known to ancients",
      moons: 82,
      orbitalPeriod: "29.5 Earth years"
    },
    {
      id: 'uranus',
      name: "URANUS",
      radius: 34,
      size: 0.4,
      color: "#ACE5EE",
      speed: 0.1,
      texture: "/2k_uranus.jpg",
      info: "An ice giant that rotates on its side (98° tilt). Uranus has the coldest atmosphere in the solar system (-224°C) and 13 faint rings. Its blue-green color comes from methane in the atmosphere.",
      class: "ICE GIANT",
      gravity: "0.89G",
      temp: "76K",
      atmosphere: "H₂ (83%), He (15%), CH₄ (2%)",
      hasRings: false,
      inclination: 0.8,
      music: '/sound.mp3',
      discovery: "1781 by William Herschel",
      moons: 27,
      orbitalPeriod: "84 Earth years"
    },
    {
      id: 'neptune',
      name: "NEPTUNE",
      radius: 40,
      size: 0.39,
      color: "#5B5DDF",
      speed: 0.07,
      texture: "/2k_neptune.jpg",
      info: "The windiest planet with the strongest winds in the solar system (2,100 km/h). Neptune was the first planet located through mathematical predictions. It radiates more heat than it receives from the Sun.",
      class: "ICE GIANT",
      gravity: "1.14G",
      temp: "72K",
      atmosphere: "H₂ (80%), He (19%), CH₄ (1%)",
      hasRings: false,
      inclination: 1.8,
      music: '/sound.mp3',
      discovery: "1846 (predicted 1845)",
      moons: 14,
      orbitalPeriod: "165 Earth years"
    }
  ]